# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 660bb66f52cc0b97a605f8813ce790a79c88e50274af3585c7aad64ea3e5019198ca06506a7ee4bce72c09716081a950b87a46c1317f86bb6d21c242a30cc113

test:
  secret_key_base: 0262ab2cf2fc63885a6578005fa93aab11220455356b57aeb354a3fc3fbe7e81859e69b0aea1c0c06d4edfb35cf72371befedc2477c1dc7ffdaf89fdcd246710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
